services:
  - type: web
    name: sih-andhra-advisory
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./andhra_hyperlocal.db
