from typing import Dict, List, Any

BUSINESS_CATEGORIES: List[Dict[str, Any]] = [
    {
        "slug": "agriculture_farming",
        "icon": "Sprout",
        "name_en": "Agriculture & Farming",
        "name_te": "వ్యవసాయం మరియు సాగు",
        "name_hi": "कृषि और खेती",
        "description": "Farming, nursery, farm inputs, and agri-services in Andhra Pradesh",
        "ideas": [
            {"slug": "vegetable_farming", "name_en": "Vegetable Farming", "name_te": "కూరగాయల సాగు", "name_hi": "सब्जी की खेती"},
            {"slug": "fruit_farming", "name_en": "Fruit Farming", "name_te": "పండ్ల తోటలు", "name_hi": "फलों की खेती"},
            {"slug": "organic_farming", "name_en": "Organic Farming", "name_te": "సేంద్రీయ వ్యవసాయం", "name_hi": "जैविक खेती"},
            {"slug": "flower_farming", "name_en": "Flower Farming", "name_te": "పూల సాగు", "name_hi": "फूलों की खेती"},
            {"slug": "nursery", "name_en": "Plant Nursery", "name_te": "మొక్కల నర్సరీ", "name_hi": "पौधशाला / नर्सरी"},
            {"slug": "seed_business", "name_en": "Seed Business", "name_te": "విత్తనాల వ్యాపారం", "name_hi": "बीज व्यवसाय"},
            {"slug": "fertilizer_shop", "name_en": "Fertilizer Shop", "name_te": "ఎరువుల దుకాణం", "name_hi": "उर्वरक की दुकान"},
            {"slug": "pesticide_shop", "name_en": "Pesticide Shop", "name_te": "పురుగుమందుల దుకాణం", "name_hi": "कीटनाशक की दुकान"},
            {"slug": "agri_equipment_rental", "name_en": "Agricultural Equipment Rental", "name_te": "వ్యవసాయ పనిముట్ల అద్దె", "name_hi": "कृषि उपकरण किराया"},
            {"slug": "farm_machinery_rental", "name_en": "Farm Machinery Rental", "name_te": "ఫామ్ మెషినరీ అద్దె", "name_hi": "कृषि मशीनरी किराया"},
            {"slug": "irrigation_equipment", "name_en": "Irrigation Equipment", "name_te": "నీటిపారుదల పరికరాలు", "name_hi": "सिंचाई उपकरण"},
            {"slug": "drip_irrigation_services", "name_en": "Drip Irrigation Services", "name_te": "బిందు సేద్యం సేవలు", "name_hi": "ड्रिप सिंचाई सेवाएं"},
            {"slug": "greenhouse_farming", "name_en": "Greenhouse Farming", "name_te": "గ్రీన్‌హౌస్ సాగు", "name_hi": "ग्रीनहाउस खेती"},
            {"slug": "mushroom_farming", "name_en": "Mushroom Farming", "name_te": "పుట్టగొడుగుల పెంపకం", "name_hi": "मशरूम की खेती"},
            {"slug": "beekeeping", "name_en": "Beekeeping (Apiculture)", "name_te": "తేనెటీగల పెంపకం", "name_hi": "मधुमक्खी पालन"},
            {"slug": "vermicomposting", "name_en": "Vermicomposting", "name_te": "వర్మి కంపోస్ట్ తయారీ", "name_hi": "वर्मीकम्पोस्टिंग"},
            {"slug": "compost_production", "name_en": "Compost Production", "name_te": "కంపోస్ట్ ఎరువుల ఉత్పత్తి", "name_hi": "खाद उत्पादन"},
            {"slug": "agri_processing", "name_en": "Agricultural Processing", "name_te": "వ్యవసాయ ఉత్పత్తుల ప్రాసెసింగ్", "name_hi": "कृषि प्रसंस्करण"}
        ]
    },
    {
        "slug": "dairy_livestock",
        "icon": "Milk",
        "name_en": "Dairy & Livestock",
        "name_te": "పాడిపరిశ్రమ & పశుసంవర్ధక",
        "name_hi": "डेयरी और पशुधन",
        "description": "Milk production, livestock rearing, cattle feed and allied animal husbandry",
        "ideas": [
            {"slug": "dairy_farm", "name_en": "Dairy Farm", "name_te": "పాడి ఫారమ్ (డెయిరీ)", "name_hi": "डेयरी फार्म"},
            {"slug": "milk_collection_centre", "name_en": "Milk Collection Centre", "name_te": "పాల సేకరణ కేంద్రం", "name_hi": "दूध संकलन केंद्र"},
            {"slug": "milk_products", "name_en": "Milk Products (Ghee, Curd, Paneer)", "name_te": "పాల ఉత్పత్తులు (నెయ్యి, పెరుగు, పన్నీర్)", "name_hi": "दुग्ध उत्पाद (घी, दही, पनीर)"},
            {"slug": "cattle_feed_shop", "name_en": "Cattle Feed Shop", "name_te": "పశుగ్రాసం / దాణా దుకాణం", "name_hi": "पशु आहार की दुकान"},
            {"slug": "goat_farming", "name_en": "Goat Farming", "name_te": "మేకల పెంపకం", "name_hi": "बकरी पालन"},
            {"slug": "sheep_farming", "name_en": "Sheep Farming", "name_te": "గొర్రెల పెంపకం", "name_hi": "भेड़ पालन"},
            {"slug": "poultry_farming", "name_en": "Poultry Farming", "name_te": "కోళ్ల ఫారమ్", "name_hi": "मुर्गी पालन"},
            {"slug": "egg_production", "name_en": "Egg Production", "name_te": "గుడ్ల ఉత్పత్తి & వ్యాపారం", "name_hi": "अंडा उत्पादन"},
            {"slug": "meat_production", "name_en": "Meat Production / Retail", "name_te": "మాంసం వ్యాపారం", "name_hi": "मांस व्यवसाय"},
            {"slug": "animal_feed", "name_en": "Animal Feed Manufacturing", "name_te": "పశువుల దాణా తయారీ", "name_hi": "पशु चारा निर्माण"}
        ]
    },
    {
        "slug": "food_beverages",
        "icon": "Utensils",
        "name_en": "Food & Beverages",
        "name_te": "ఆహారం & పానీయాలు",
        "name_hi": "खाद्य और पेय",
        "description": "Eateries, bakeries, snacks, mills, and food processing",
        "ideas": [
            {"slug": "bakery", "name_en": "Bakery & Cake Shop", "name_te": "బేకరీ & కేక్ షాప్", "name_hi": "बेकरी और केक शॉप"},
            {"slug": "restaurant", "name_en": "Restaurant", "name_te": "రెస్టారెంట్", "name_hi": "रेस्टोरेंट / भोजनालय"},
            {"slug": "small_hotel", "name_en": "Small Hotel / Mess", "name_te": "హోటల్ / మెస్", "name_hi": "छोटा होटल / मेस"},
            {"slug": "tea_shop", "name_en": "Tea & Coffee Shop", "name_te": "టీ / కాఫీ దుకాణం", "name_hi": "चाय और कॉफी की दुकान"},
            {"slug": "juice_shop", "name_en": "Fresh Juice Shop", "name_te": "జ్యూస్ షాప్", "name_hi": "जूस की दुकान"},
            {"slug": "tiffin_centre", "name_en": "Tiffin Centre", "name_te": "టిఫిన్ సెంటర్", "name_hi": "टिफिन सेंटर"},
            {"slug": "fast_food", "name_en": "Fast Food Corner", "name_te": "ఫాస్ట్ ఫుడ్ కార్నర్", "name_hi": "फास्ट फूड"},
            {"slug": "catering", "name_en": "Catering Services", "name_te": "కేటరింగ్ సర్వీసెస్", "name_hi": "खानपान सेवाएं"},
            {"slug": "cloud_kitchen", "name_en": "Cloud Kitchen", "name_te": "క్లౌడ్ కిచెన్", "name_hi": "क्लाउड किचन"},
            {"slug": "sweet_shop", "name_en": "Sweet Shop (Mithai)", "name_te": "స్వీట్ షాప్", "name_hi": "मिठाई की दुकान"},
            {"slug": "snacks", "name_en": "Snacks & Savouries (Namkeen)", "name_te": "పిండివంటలు / స్నాక్స్", "name_hi": "नमकीन और स्नैक्स"},
            {"slug": "food_processing", "name_en": "Food Processing Unit", "name_te": "ఆహార ప్రాసెసింగ్ యూనిట్", "name_hi": "खाद्य प्रसंस्करण"},
            {"slug": "pickle_business", "name_en": "Pickle Business (Pachadi)", "name_te": "పచ్చళ్ల వ్యాపారం", "name_hi": "अचार का व्यवसाय"},
            {"slug": "spice_processing", "name_en": "Spice & Masala Grinding", "name_te": "మసాలా పొడుల తయారీ", "name_hi": "मसाला पिसाई और प्रसंस्करण"},
            {"slug": "flour_mill", "name_en": "Flour Mill (Pindi Girni)", "name_te": "పిండి గిర్నీ", "name_hi": "आटा चक्की"},
            {"slug": "rice_mill", "name_en": "Mini Rice Mill", "name_te": "రైస్ మిల్లు", "name_hi": "मिनी चावल मिल"}
        ]
    },
    {
        "slug": "retail",
        "icon": "ShoppingCart",
        "name_en": "Retail & Stores",
        "name_te": "కిరాణా & చిల్లర వర్తకం",
        "name_hi": "खुदरा और किराना",
        "description": "Kirana, supermarkets, apparel, electronics, and daily essentials",
        "ideas": [
            {"slug": "grocery_shop", "name_en": "Kirana / Grocery Shop", "name_te": "కిరాణా దుకాణం", "name_hi": "किराना दुकान"},
            {"slug": "supermarket", "name_en": "Mini Supermarket", "name_te": "మినీ సూపర్ మార్కెట్", "name_hi": "मिनी सुपरमार्केट"},
            {"slug": "vegetable_shop", "name_en": "Vegetable & Greens Stall", "name_te": "కూరగాయల కొట్టు", "name_hi": "सब्जी की दुकान"},
            {"slug": "fruit_shop", "name_en": "Fresh Fruit Stall", "name_te": "పండ్ల దుకాణం", "name_hi": "फलों की दुकान"},
            {"slug": "clothing", "name_en": "Clothing & Ready-mades", "name_te": "బట్టల దుకాణం", "name_hi": "कपड़ों की दुकान"},
            {"slug": "footwear", "name_en": "Footwear Shop", "name_te": "చెప్పుల దుకాణం", "name_hi": "जूते-चप्पल की दुकान"},
            {"slug": "stationery", "name_en": "Stationery & Book Stall", "name_te": "స్టేషనరీ & పుస్తకాల దుకాణం", "name_hi": "स्टेशनरी की दुकान"},
            {"slug": "hardware", "name_en": "Hardware & Paints", "name_te": "హార్డ్‌వేర్ & పెయింట్స్", "name_hi": "हार्डवेयर की दुकान"},
            {"slug": "electrical_shop", "name_en": "Electrical Goods", "name_te": "ఎలక్ట్రికల్ సామాగ్రి", "name_hi": "इलेक्ट्रिकल सामान"},
            {"slug": "electronics", "name_en": "Electronics & Appliances", "name_te": "ఎలక్ట్రానిక్స్ దుకాణం", "name_hi": "इलेक्ट्रॉनिक्स"},
            {"slug": "mobile_accessories", "name_en": "Mobile Accessories & Covers", "name_te": "మొబైల్ యాక్సెసరీస్", "name_hi": "मोबाइल एक्सेसरीज"},
            {"slug": "household_goods", "name_en": "Household & Plastic Goods", "name_te": "గృహోపకరణాలు / ప్లాస్టిక్ సామాన్లు", "name_hi": "घरेलू सामान"},
            {"slug": "cosmetic_shop", "name_en": "Cosmetic & Fancy Store", "name_te": "ఫ్యాన్సీ & కాస్మెటిక్ స్టోర్", "name_hi": "कॉस्मेटिक और फैंसी स्टोर"}
        ]
    },
    {
        "slug": "services",
        "icon": "Wrench",
        "name_en": "Services & Repairs",
        "name_te": "సేవలు & మరమ్మతులు",
        "name_hi": "सेवाएं और मरम्मत",
        "description": "Repairs, salons, tailoring, laundry, and daily maintenance services",
        "ideas": [
            {"slug": "mobile_repair", "name_en": "Mobile Phone Repair", "name_te": "మొబైల్ రిపేర్", "name_hi": "मोबाइल रिपेयरिंग"},
            {"slug": "computer_repair", "name_en": "Computer & Laptop Repair", "name_te": "కంప్యూటర్ మరమ్మతులు", "name_hi": "कंप्यूटर मरम्मत"},
            {"slug": "electronics_repair", "name_en": "TV & Home Appliance Repair", "name_te": "టీవీ & గృహోపకరణాల రిపేర్", "name_hi": "उपकरण मरम्मत"},
            {"slug": "vehicle_repair", "name_en": "Automobile Workshop", "name_te": "ఆటోమొబైల్ వర్క్‌షాప్", "name_hi": "वाहन मरम्मत"},
            {"slug": "two_wheeler_service", "name_en": "Two-Wheeler Service Centre", "name_te": "టూ-వీలర్ మెకానిక్ షాప్", "name_hi": "दोपहिया सर्विस"},
            {"slug": "car_washing", "name_en": "Vehicle Washing & Detailing", "name_te": "వాహనాల వాషింగ్ సెంటర్", "name_hi": "कार/बाइक वाशिंग"},
            {"slug": "laundry", "name_en": "Laundry & Ironing", "name_te": "లాండ్రీ & ఇస్త్రీ సర్వీస్", "name_hi": "लॉन्ड्री और इस्त्री"},
            {"slug": "tailoring", "name_en": "Tailoring & Boutique", "name_te": "టైలరింగ్ & లేడీస్ బొటీక్", "name_hi": "सिलाई और बुटीक"},
            {"slug": "beauty_salon", "name_en": "Beauty Parlour / Salon", "name_te": "బ్యూటీ పార్లర్", "name_hi": "ब्यूटी पार्लर"},
            {"slug": "barber", "name_en": "Men's Barber Shop", "name_te": "మెన్స్ క్షౌరశాల", "name_hi": "नाई की दुकान"},
            {"slug": "photography", "name_en": "Photo & Video Studio", "name_te": "ఫోటో స్టూడియో", "name_hi": "फोटो स्टूडियो"},
            {"slug": "printing", "name_en": "Printing & Xerox Shop", "name_te": "జిరాక్స్ & ప్రింటింగ్ షాప్", "name_hi": "प्रिंटिंग और ज़ेरॉक्स"},
            {"slug": "internet_centre", "name_en": "Internet & MeeSeva Point", "name_te": "మీసేవ / ఇంటర్నెట్ సెంటర్", "name_hi": "इंटरनेट कैफे / ई-सेवा"},
            {"slug": "digital_services_centre", "name_en": "Digital Services & Online Forms", "name_te": "ఆన్‌లైన్ దరఖాస్తు కేంద్రం", "name_hi": "डिजिटल सेवा केंद्र"},
            {"slug": "courier", "name_en": "Courier & Parcel Booking", "name_te": "కొరియర్ & పార్శిల్ సర్వీస్", "name_hi": "कूरियर सेवा"},
            {"slug": "delivery", "name_en": "Local Delivery Service", "name_te": "స్థానిక డెలివరీ సర్వీస్", "name_hi": "डिलीवरी सेवा"},
            {"slug": "cleaning", "name_en": "Domestic & Commercial Cleaning", "name_te": "క్లీనింగ్ సర్వీసెస్", "name_hi": "सफाई सेवा"},
            {"slug": "pest_control", "name_en": "Pest Control Services", "name_te": "కీటకాల నివారణ సేవలు", "name_hi": "कीट नियंत्रण"}
        ]
    },
    {
        "slug": "manufacturing",
        "icon": "Hammer",
        "name_en": "Manufacturing & Crafts",
        "name_te": "ఉత్పత్తి & గ్రామీణ చేతివృత్తులు",
        "name_hi": "विनिर्माण और शिल्प",
        "description": "Small machinery, furniture, handicrafts, garments, and building materials",
        "ideas": [
            {"slug": "furniture", "name_en": "Wooden & Steel Furniture", "name_te": "ఫర్నిచర్ తయారీ", "name_hi": "फर्नीचर निर्माण"},
            {"slug": "candles", "name_en": "Candle & Agarbatti Making", "name_te": "కొవ్వొత్తులు & అగర్‌బత్తీల తయారీ", "name_hi": "मोमबत्ती और अगरबत्ती"},
            {"slug": "soap", "name_en": "Handmade Soap & Detergent", "name_te": "సబ్బులు & డిటర్జెంట్ తయారీ", "name_hi": "साबुन और डिटर्जेंट"},
            {"slug": "paper_products", "name_en": "Paper Bags & Cups", "name_te": "పేపర్ బ్యాగులు & కప్పులు", "name_hi": "कागज के उत्पाद"},
            {"slug": "packaging", "name_en": "Packaging Materials", "name_te": "ప్యాకేజింగ్ మెటీరియల్స్", "name_hi": "पैकेजिंग सामग्री"},
            {"slug": "handicrafts", "name_en": "Kondapalli / Etikoppaka Crafts", "name_te": "కొండపల్లి / ఏటికొప్పాక బొమ్మలు & హస్తకళలు", "name_hi": "हस्तशिल्प और खिलौने"},
            {"slug": "garments", "name_en": "Garment Manufacturing", "name_te": "దుస్తుల తయారీ యూనిట్", "name_hi": "गारमेंट निर्माण"},
            {"slug": "small_machinery", "name_en": "Fabrication & Small Machinery", "name_te": "ఫ్యాబ్రికేషన్ వర్క్స్", "name_hi": "लघु मशीनरी निर्माण"},
            {"slug": "food_products", "name_en": "Processed Food & Sweets Unit", "name_te": "ప్యాక్డ్ ఫుడ్ తయారీ", "name_hi": "खाद्य उत्पाद निर्माण"},
            {"slug": "building_materials", "name_en": "Cement Bricks & Pavers", "name_te": "సిమెంట్ ఇటుకల తయారీ", "name_hi": "ईंट और भवन निर्माण सामग्री"},
            {"slug": "metal_products", "name_en": "Metal Works & Grills", "name_te": "మెటల్ గ్రిల్స్ & గేట్లు", "name_hi": "धातु उत्पाद"},
            {"slug": "wooden_products", "name_en": "Carpentry & Woodwork", "name_te": "చెక్క సామాగ్రి", "name_hi": "लकड़ी के उत्पाद"}
        ]
    },
    {
        "slug": "transport_mobility",
        "icon": "Truck",
        "name_en": "Transport & Mobility",
        "name_te": "రవాణా & ప్రయాణ సేవలు",
        "name_hi": "परिवहन और आवागमन",
        "description": "Auto, taxi, tractor, cargo transport, and vehicle rental",
        "ideas": [
            {"slug": "auto_service", "name_en": "Auto Rickshaw Service", "name_te": "ఆటో రిక్షా సర్వీస్", "name_hi": "ऑटो रिक्शा सेवा"},
            {"slug": "taxi", "name_en": "Local Taxi / Cab Service", "name_te": "క్యాబ్ / టాక్సీ సర్వీస్", "name_hi": "टैक्सी सेवा"},
            {"slug": "local_delivery", "name_en": "Local Goods Delivery", "name_te": "సామాగ్రి రవాణా సర్వీస్", "name_hi": "स्थानीय सामान डिलीवरी"},
            {"slug": "goods_transport", "name_en": "Mini Truck Goods Transport", "name_te": "మినీ లారీ / గూడ్స్ రవాణా", "name_hi": "माल ढुलाई परिवहन"},
            {"slug": "tractor_rental", "name_en": "Tractor & Trolley Rental", "name_te": "ట్రాక్టర్ & ట్రాలీ అద్దె", "name_hi": "ट्रैक्टर किराया"},
            {"slug": "farm_vehicle_rental", "name_en": "Harvester & Farm Vehicle Rental", "name_te": "వ్యవసాయ వాహనాల అద్దె", "name_hi": "कृषि वाहन किराया"},
            {"slug": "two_wheeler_rental", "name_en": "Bike / Scooter Rental", "name_te": "ద్విచక్ర వాహనాల అద్దె", "name_hi": "दोपहिया वाहन किराया"},
            {"slug": "logistics", "name_en": "Rural Logistics & Agri Freight", "name_te": "గ్రామీణ లాజిస్టిక్స్", "name_hi": "ग्रामीण लॉजिस्टिक्स"}
        ]
    },
    {
        "slug": "education",
        "icon": "BookOpen",
        "name_en": "Education & Coaching",
        "name_te": "విద్య & శిక్షణ",
        "name_hi": "शिक्षा और कोचिंग",
        "description": "Tuitions, computer institutes, skill courses, and vocational centers",
        "ideas": [
            {"slug": "tuition", "name_en": "School Tuition Point", "name_te": "స్కూల్ ట్యూషన్ పాయింట్", "name_hi": "ट्यूशन सेंटर"},
            {"slug": "coaching", "name_en": "Competitive Exam Coaching", "name_te": "పోటీ పరీక్షల కోచింగ్ సెంటర్", "name_hi": "प्रतियोगी परीक्षा कोचिंग"},
            {"slug": "computer_training", "name_en": "Computer Education Institute", "name_te": "కంప్యూటర్ శిక్షణా కేంద్రం", "name_hi": "कंप्यूटर प्रशिक्षण"},
            {"slug": "skill_training", "name_en": "Youth Skill Development", "name_te": "యువజన నైపుణ్య శిక్షణ", "name_hi": "कौशल प्रशिक्षण केंद्र"},
            {"slug": "language_training", "name_en": "Spoken English & Communication", "name_te": "స్పోకెన్ ఇంగ్లీష్ కేంద్రం", "name_hi": "अंग्रेजी भाषा प्रशिक्षण"},
            {"slug": "vocational_training", "name_en": "Tailoring & Technical Skills", "name_te": "వృత్తి విద్యా శిక్షణ", "name_hi": "व्यावसायिक प्रशिक्षण"},
            {"slug": "educational_materials", "name_en": "School Supplies & Notes", "name_te": "స్టడీ మెటీరియల్స్ & గైడ్స్", "name_hi": "शैक्षणिक सामग्री"}
        ]
    },
    {
        "slug": "tourism_hospitality",
        "icon": "Hotel",
        "name_en": "Tourism & Hospitality",
        "name_te": "పర్యాటకం & ఆతిథ్యం",
        "name_hi": "पर्यटन और आतिथ्य",
        "description": "Homestays, pilgrimage lodging, travel guides, and local tourism",
        "ideas": [
            {"slug": "homestay", "name_en": "Village Homestay", "name_te": "గ్రామీణ హోమ్‌స్టే", "name_hi": "होमस्टे"},
            {"slug": "small_hotel", "name_en": "Lodge / Guest House", "name_te": "లాడ్జ్ / గెస్ట్ హౌస్", "name_hi": "लॉज / गेस्ट हाउस"},
            {"slug": "guest_house", "name_en": "Pilgrimage Rest House", "name_te": "యాత్రికుల వసతి గృహం", "name_hi": "यात्री निवास"},
            {"slug": "tourist_guide", "name_en": "Temple & Nature Guide", "name_te": "టూరిస్ట్ గైడ్ సర్వీస్", "name_hi": "पर्यटक गाइड"},
            {"slug": "local_transport", "name_en": "Tourist Sightseeing Cabs", "name_te": "దర్శనీయ స్థలాల రవాణా", "name_hi": "पर्यटन वाहन"},
            {"slug": "travel_service", "name_en": "Tours & Ticket Booking", "name_te": "ట్రావెల్ & టికెట్ బుకింగ్", "name_hi": "यात्रा और टिकट सेवा"},
            {"slug": "handicrafts_souvenirs", "name_en": "AP Souvenirs & Kalamkari", "name_te": "కలంకారి & చేనేత సావనీర్లు", "name_hi": "हस्तशिल्प और स्मृति चिन्ह"},
            {"slug": "local_food_experience", "name_en": "Authentic Andhra Food Stall", "name_te": "సాంప్రదాయ ఆంధ్రా భోజన శాల", "name_hi": "पारंपरिक भोजन अनुभव"}
        ]
    },
    {
        "slug": "digital_services",
        "icon": "Laptop",
        "name_en": "Digital Services & IT",
        "name_te": "డిజిటల్ సేవలు & ఐటీ",
        "name_hi": "डिजिटल सेवाएं और आईटी",
        "description": "Common service centers, design, online forms, and cyber support",
        "ideas": [
            {"slug": "computer_centre", "name_en": "Digital E-Seva Centre", "name_te": "ఈ-సేవ / డిజిటల్ కేంద్రం", "name_hi": "कंप्यूटर व ई-सेवा केंद्र"},
            {"slug": "digital_service_centre", "name_en": "Gramin Digital Point (MeeSeva)", "name_te": "గ్రామీణ డిజిటల్ పాయింట్", "name_hi": "ग्रामीण डिजिटल सेवा"},
            {"slug": "website_services", "name_en": "Local Business Website Setup", "name_te": "వెబ్‌సైట్ డిజైనింగ్ సేవలు", "name_hi": "वेबसाइट निर्माण"},
            {"slug": "graphic_design", "name_en": "Flex & Banner Designing", "name_te": "ఫ్లెక్స్ & బ్యానర్ డిజైనింగ్", "name_hi": "ग्राफिक डिजाइनिंग"},
            {"slug": "digital_marketing", "name_en": "WhatsApp & Local Promotion", "name_te": "లోకల్ డిజిటల్ ప్రచారం", "name_hi": "डिजिटल मार्केटिंग"},
            {"slug": "mobile_app_services", "name_en": "Smart Device Setup & Support", "name_te": "స్మార్ట్ డివైస్ సపోర్ట్", "name_hi": "स्मार्टफोन व ऐप सेवा"},
            {"slug": "online_form_services", "name_en": "Govt Scheme Applications & PAN", "name_te": "ప్రభుత్వ పథకాల దరఖాస్తు సేవలు", "name_hi": "ऑनलाइन फॉर्म व योजनाएं"},
            {"slug": "cyber_services", "name_en": "Cyber & Scanning Point", "name_te": "స్కానింగ్ & ప్రింట్ పాయింట్", "name_hi": "साइबर कैफे"},
            {"slug": "it_training", "name_en": "Basic IT & Tally Skills", "name_te": "ట్యాలీ & బేసిక్ ఐటీ శిక్షణ", "name_hi": "आईटी प्रशिक्षण"}
        ]
    },
    {
        "slug": "environment_sustainability",
        "icon": "Leaf",
        "name_en": "Environment & Green Energy",
        "name_te": "పర్యావరణం & గ్రీన్ ఎనర్జీ",
        "name_hi": "पर्यावरण और सौर ऊर्जा",
        "description": "Solar installations, water purification, waste recycling, and bio-manure",
        "ideas": [
            {"slug": "waste_collection", "name_en": "Dry Waste & Scrap Collection", "name_te": "స్క్రాప్ & రీసైక్లింగ్ సేకరణ", "name_hi": "कचरा संग्रह व कबाड़ी"},
            {"slug": "recycling", "name_en": "Plastic & Paper Recycling", "name_te": "ప్లాస్టిక్ & పేపర్ రీసైక్లింగ్", "name_hi": "पुनर्चक्रण (रीसाइक्लिंग)"},
            {"slug": "composting", "name_en": "Bio-waste Composting", "name_te": "వ్యర్థాలతో ఎరువుల తయారీ", "name_hi": "जैविक खाद निर्माण"},
            {"slug": "solar_services", "name_en": "Rooftop Solar Pump/Panel Installation", "name_te": "సోలార్ పంపులు / ప్యానెల్ బిగింపు", "name_hi": "सोलर पैनल स्थापना"},
            {"slug": "solar_maintenance", "name_en": "Solar Panel Cleaning & Maintenance", "name_te": "సోలార్ ప్యానెల్ క్లీనింగ్ & సర్వీస్", "name_hi": "सोलर पैनल रखरखाव"},
            {"slug": "water_purification", "name_en": "RO Drinking Water Plant (20L Cans)", "name_te": "మినరల్ వాటర్ ప్లాంట్ (RO వాటర్ క్యాన్స్)", "name_hi": "पेयजल शोधन संयंत्र"},
            {"slug": "water_supply", "name_en": "Safe Water Supply & Tankers", "name_te": "తాగునీటి సరఫరా సర్వీస్", "name_hi": "जल आपूर्ति"},
            {"slug": "rainwater_harvesting", "name_en": "Rainwater Harvesting Construction", "name_te": "వర్షపు నీటి నిల్వ ఇంకుడు గుంతలు", "name_hi": "वर्षा जल संचयन सेवा"},
            {"slug": "renewable_energy", "name_en": "Biogas & Green Energy Support", "name_te": "బయోగ్యాస్ ప్లాంట్ సేవలు", "name_hi": "बायोगैस व हरित ऊर्जा"}
        ]
    }
]

# Quick lookup mappings for profiles
CATEGORY_MAP: Dict[str, Dict[str, Any]] = {c["slug"]: c for c in BUSINESS_CATEGORIES}

# Business Domain Profiles with Strict Relevance Isolation
DEFAULT_PROFILES: Dict[str, Dict[str, Any]] = {
    "restaurant": {
        "business_name": "Restaurant",
        "category_slug": "food_beverages",
        "search_keywords": ["restaurant", "hotel", "mess", "tiffin", "bhojanam", "dhaba", "fast food", "biryani", "canteen", "kitchen", "eatery", "రెస్టారెంట్", "హోటల్", "టిఫిన్", "మెస్", "ధాబా", "బిర్యానీ", "భోజనం", "रेस्टोरेंट", "होटल", "ढाबा", "भोजनालय"],
        "competitor_keywords": ["restaurant", "hotel", "mess", "dhaba", "biryani", "bhojanam", "kitchen", "canteen", "eatery", "food court", "fast food", "diner", "tiffins", "tiffin centre", "meals", "parlour", "bhojan", "mandhi", "రెస్టారెంట్", "హోటల్", "మెస్", "ధాబా", "బిర్యానీ", "భోజనం", "టిఫిన్", "रेस्टोरेंट", "होटल", "ढाबा", "भोजनालय", "मेस"],
        "direct_osm_tags": ["amenity=restaurant", "amenity=fast_food", "amenity=food_court"],
        "indirect_osm_tags": ["amenity=cafe", "shop=bakery", "shop=pastry", "amenity=ice_cream", "shop=sweets"],
        "indirect_keywords": ["cafe", "coffee", "tea", "bakery", "sweets", "juice", "snacks", "chaat", "కాఫీ", "టీ", "బేకరీ", "స్వీట్స్", "चाय", "कॉफ़ी", "बेकरी"],
        "exclude_osm_tags": ["shop=supermarket", "shop=convenience", "shop=grocery", "shop=dairy", "shop=clothes", "shop=hardware", "craft=dairy", "shop=chemist", "amenity=marketplace"],
        "exclude_keywords": ["supermarket", "mart", "dmart", "d-mart", "more", "spencer", "walmart", "kirana", "grocery", "dairy", "diary", "milk", "sangam", "visakha dairy", "dodla", "heritage", "medical", "pharmacy", "repair", "hardware", "fertilizer", "cloth", "footwear", "marketplace"],
        "supporting_poi_tags": ["highway=bus_stop", "amenity=bank", "amenity=cinema", "amenity=hospital", "amenity=college"],
        "customer_segments": ["Families & Dine-in Diners", "Office Workers & Daily Commuters", "Highway Travelers & Bus Passengers", "Parcel & Delivery Customers"],
        "supplier_categories": ["APMC Mandi Vegetable Traders", "Local Poultry & Meat Vendors", "Dairy / Paneer / Ghee Suppliers", "Commercial Rice & Grocery Wholesalers", "Commercial LPG Distributors"],
        "infrastructure_requirements": ["Commercial Kitchen Space & Exhaust Chimney", "Adequate Seating & Clean Drinking Water", "Dedicated Power Line for Freezers", "Two-Wheeler / Auto Parking"],
        "relevant_demographics": ["Local Population & Commuter Traffic", "Office & Educational Footfall", "Income & Eating-Out Frequency"],
        "relevant_environmental_factors": ["Heat & Spoilage Prevention for Perishables", "Monsoon Dining Footfall Patterns"],
        "relevant_risk_factors": ["High Food Waste & Perishable Spoilage", "Kitchen Staff Attrition & Chef Dependency", "Working Capital for Daily Raw Material Purchases"],
        "relevant_price_indicators": ["Veg Meal Thali: ₹80-₹120", "Chicken Biryani: ₹160-₹240", "Tea / Coffee: ₹12-₹20", "South Indian Tiffin (Idli/Dosa): ₹35-₹60"],
        "relevant_accessibility_factors": ["Main Road Visibility", "Proximity to Bus Stand, Junction, or Market Hub"]
    },
    "tiffin_centre": {
        "business_name": "Tiffin Centre",
        "category_slug": "food_beverages",
        "search_keywords": ["tiffin", "idli", "dosa", "breakfast", "tea", "coffee", "fast food", "టిఫిన్", "ఇడ్లీ", "దోశ", "హోటల్", "నాష్తా", "टिफिन"],
        "competitor_keywords": ["tiffin", "tiffin centre", "hotel", "fast food", "mess", "idli", "dosa", "tea", "parlour", "food court", "breakfast", "snacks", "టిఫిన్", "హోటల్", "మెస్", "నాష్తా"],
        "direct_osm_tags": ["amenity=fast_food", "amenity=restaurant", "amenity=cafe"],
        "indirect_osm_tags": ["shop=bakery", "shop=sweets", "amenity=ice_cream"],
        "indirect_keywords": ["bakery", "sweets", "snacks", "juice", "tea", "coffee"],
        "exclude_osm_tags": ["shop=supermarket", "shop=convenience", "shop=grocery", "shop=dairy", "shop=clothes", "shop=hardware", "amenity=marketplace"],
        "exclude_keywords": ["supermarket", "mart", "dmart", "more", "spencer", "walmart", "kirana", "grocery", "dairy", "diary", "milk", "medical", "pharmacy", "repair", "marketplace"],
        "supporting_poi_tags": ["highway=bus_stop", "amenity=college", "amenity=bank"],
        "customer_segments": ["Morning Commuters & Daily Workers", "Students & College Youths", "Evening Snack Seekers"],
        "supplier_categories": ["Rice & Urad Dal Wholesalers", "Vegetable & Chutney Suppliers", "Milk & Dairy Agents"],
        "infrastructure_requirements": ["Commercial Stove & Wet Grinder", "Running Water & Wash Basin", "UPI / QR Soundbox"],
        "relevant_demographics": ["Morning & Evening Pedestrian Flow", "Bus Station / Auto Stand Junction Activity"],
        "relevant_environmental_factors": ["Monsoon Protection (Covered Awning)"],
        "relevant_risk_factors": ["Short Peak-Hour Window (7am-11am, 5pm-9pm)", "Flour & Cooking Oil Inflation"],
        "relevant_price_indicators": ["Plate Idli (4 pcs): ₹30-₹40", "Masala Dosa: ₹40-₹60", "Filter Coffee / Tea: ₹12-₹15"],
        "relevant_accessibility_factors": ["High Morning Walking Traffic", "Near Junction / Auto Stand"]
    },
    "tea_shop": {
        "business_name": "Tea & Coffee Shop",
        "category_slug": "food_beverages",
        "search_keywords": ["tea", "coffee", "chai", "cafe", "juice", "టీ", "కాఫీ", "చాయ్", "జ్యూస్", "चाय", "कॉफ़ी"],
        "competitor_keywords": ["tea", "chai", "coffee", "cafe", "juice", "beverages", "tea stall", "tea point", "టీ", "కాఫీ", "చాయ్", "चाय"],
        "direct_osm_tags": ["amenity=cafe", "shop=tea", "shop=beverages"],
        "indirect_osm_tags": ["amenity=fast_food", "shop=bakery"],
        "indirect_keywords": ["bakery", "fast food", "snacks", "tiffin"],
        "exclude_osm_tags": ["shop=supermarket", "shop=convenience", "shop=grocery", "shop=dairy", "amenity=marketplace"],
        "exclude_keywords": ["supermarket", "mart", "dmart", "more", "kirana", "grocery", "dairy", "diary", "milk", "medical", "marketplace"],
        "supporting_poi_tags": ["highway=bus_stop", "amenity=bank", "amenity=hospital"],
        "customer_segments": ["Daily Commuters & Passersby", "Office & Shop Workers", "Students & Youth Groups"],
        "supplier_categories": ["Milk Dairies & Milk Vendors", "Tea Dust & Coffee Powder Distributors", "Paper Cup & Disposable Vendors"],
        "infrastructure_requirements": ["Gas Stove / Water Boiler", "Small Counter & Drainage", "UPI QR Display"],
        "relevant_demographics": ["Pedestrian Junction Footfall", "Shop Density Around Location"],
        "relevant_environmental_factors": ["Rain Sheltering for Customers"],
        "relevant_risk_factors": ["Low Average Ticket Size requiring high volume", "Milk Price Fluctuations"],
        "relevant_price_indicators": ["Irani / Special Tea: ₹10-₹15", "Filter Coffee: ₹15-₹20", "Cold Juice: ₹30-₹50"],
        "relevant_accessibility_factors": ["Corner Junction Visibility", "Immediate Roadfront Access"]
    },
    "dairy_farm": {
        "business_name": "Dairy Farm",
        "category_slug": "dairy_livestock",
        "search_keywords": ["dairy", "milk", "cattle", "buffalo", "ghee", "పాడి", "పాలు", "డెయిరీ", "दूध", "डेयरी"],
        "competitor_keywords": ["dairy", "milk collection", "vijaya dairy", "sangam dairy", "visakha dairy", "dodla", "heritage", "amul", "milk chilling", "dairy farm", "పాడి", "పాలు", "డెయిరీ", "दूध", "डेयरी"],
        "direct_osm_tags": ["shop=dairy", "craft=dairy", "building=cowshed", "landuse=farmyard"],
        "indirect_osm_tags": ["shop=farm"],
        "indirect_keywords": ["cattle", "livestock", "fodder"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "amenity=cafe", "shop=supermarket", "shop=convenience", "shop=grocery", "shop=clothes", "shop=hardware"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "dhaba", "biryani", "supermarket", "mart", "dmart", "more", "spencer", "kirana", "grocery", "repair", "hardware", "barber"],
        "supporting_poi_tags": ["amenity=veterinary", "shop=agrarian", "office=government"],
        "customer_segments": ["Rural & Town Households", "Tea Stalls & Tiffin Centres", "Local Sweet Shops", "Milk Procurement Cooperatives (Visakha/Sangam/Vijaya)"],
        "supplier_categories": ["Fodder & Silage Growers", "Veterinary Clinics", "Cattle Feed Mills", "AP Rythu Bharosa Kendras (RBKs)"],
        "infrastructure_requirements": ["Continuous Water Supply", "Electricity for Chilling/Aeration", "Road Access for Daily Milk Van Pickups", "Shaded Cattle Sheds"],
        "relevant_demographics": ["Total Households in 5-10km", "Number of Small Eateries & Tea Stalls", "Livestock density in District"],
        "relevant_environmental_factors": ["High Summer Heat Stress", "Monsoon Waterlogging Risk", "Fodder Availability Index"],
        "relevant_risk_factors": ["Cattle Disease Outbreaks (FMD/Lumpy)", "Fodder Price Inflation", "Perishable Spoilage without Cold Chain"],
        "relevant_price_indicators": ["Farmgate Cow Milk: ₹38-₹44/L", "Farmgate Buffalo Milk: ₹58-₹68/L", "Concentrate Feed: ₹22-₹26/kg"],
        "relevant_accessibility_factors": ["Proximity to All-Weather Road (< 1.5 km)", "Distance to Nearest BMC (Bulk Milk Cooling Centre)"]
    },
    "bakery": {
        "business_name": "Bakery & Cake Shop",
        "category_slug": "food_beverages",
        "search_keywords": ["bakery", "cake", "bread", "pastry", "sweets", "బేకరీ", "కేకులు", "రొట్టెలు", "बेकरी", "केक"],
        "competitor_keywords": ["bakery", "cake shop", "pastry shop", "iyengar bakery", "hot puffs", "bakes", "confectionery", "బేకరీ", "కేకులు", "बेकरी"],
        "direct_osm_tags": ["shop=bakery", "shop=pastry", "shop=confectionery"],
        "indirect_osm_tags": ["amenity=cafe", "shop=sweets"],
        "indirect_keywords": ["cafe", "sweets", "ice cream", "desserts"],
        "exclude_osm_tags": ["shop=supermarket", "shop=grocery", "shop=dairy", "shop=convenience", "amenity=marketplace"],
        "exclude_keywords": ["supermarket", "mart", "dmart", "more", "spencer", "walmart", "kirana", "grocery", "dairy", "diary", "milk farm", "medical", "marketplace"],
        "supporting_poi_tags": ["amenity=school", "amenity=college", "amenity=bus_station", "amenity=bank"],
        "customer_segments": ["School & College Students", "Young Adults & Working Professionals", "Families for Celebrations & Birthdays", "Evening Tea Snackers"],
        "supplier_categories": ["Flour Mills (Maida/Wheat)", "Dairy Suppliers (Butter/Cream/Milk)", "Commercial LPG Distributors", "Packaging Suppliers"],
        "infrastructure_requirements": ["3-Phase Electricity for Ovens", "Display Counter Refrigeration", "Footfall Location Near Main Street"],
        "relevant_demographics": ["Youth Population (15-35 yrs)", "Household Density", "Town / Village Centre Footfall"],
        "relevant_environmental_factors": ["Humidity Management for Crispy Bakes", "Extreme Heat affecting Cream storage"],
        "relevant_risk_factors": ["Short Shelf-life of Baked Goods", "Raw Material Price Fluctuation (Maida, Sugar, Oil)", "High Rental Overhead on Main Road"],
        "relevant_price_indicators": ["Fresh White Bread (400g): ₹35-₹45", "Tea Puff (Veg/Egg): ₹15-₹25", "Standard Birthday Cake (1kg): ₹400-₹650"],
        "relevant_accessibility_factors": ["Main Road Visibility", "Two-Wheeler Parking Space", "Proximity to Bus Stop / Auto Stand"]
    },
    "grocery_shop": {
        "business_name": "Kirana / Grocery Shop",
        "category_slug": "retail",
        "search_keywords": ["grocery", "kirana", "provisions", "general store", "కిరాణా", "సరుకులు", "किराना", "दुकान"],
        "competitor_keywords": ["grocery", "kirana", "supermarket", "general store", "d-mart", "dmart", "more", "provisions", "reliance fresh", "ratnadeep", "కిరాణా", "సూపర్ మార్కెట్", "किराना"],
        "direct_osm_tags": ["shop=convenience", "shop=general", "shop=grocery", "shop=supermarket"],
        "indirect_osm_tags": ["amenity=marketplace", "shop=department_store"],
        "indirect_keywords": ["market", "bazaar", "mart"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "amenity=cafe", "shop=dairy", "craft=dairy", "shop=clothes", "shop=mobile_phone"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "dhaba", "biryani", "canteen", "cowshed", "dairy farm", "mobile repair", "barber", "tailor"],
        "supporting_poi_tags": ["residential=subdivision", "highway=bus_stop", "amenity=place_of_worship"],
        "customer_segments": ["Surrounding Residential Households", "Daily Wage Earners", "Local Village Inhabitants"],
        "supplier_categories": ["Wholesale Grain & Pulse Traders (APMC)", "FMCG Distributors", "Local Dairy Agents"],
        "infrastructure_requirements": ["Dry Storage Room", "Shelving & Display Racks", "UPI / QR Payment Terminal"],
        "relevant_demographics": ["Total Residential Households in 1-2 km", "Population Density", "Average Household Size"],
        "relevant_environmental_factors": ["Monsoon Dampness / Pest Attack on Grains", "Heat Impact on Perishables"],
        "relevant_risk_factors": ["Local Credit (Khata) Default Risk", "Competition from Discount Chains & Online Delivery"],
        "relevant_price_indicators": ["Rice (Sona Masoori, 25kg): ₹1,250-₹1,600", "Sunflower Oil (1L): ₹115-₹140", "Toor Dal (1kg): ₹145-₹175"],
        "relevant_accessibility_factors": ["Internal Village / Colony Road Proximity", "Easy Walking Distance (< 400m for households)"]
    },
    "supermarket": {
        "business_name": "Mini Supermarket",
        "category_slug": "retail",
        "search_keywords": ["supermarket", "mart", "dmart", "more", "hypermarket", "సూపర్ మార్కెట్", "మినీ మార్కెట్", "सुपरमार्केट"],
        "competitor_keywords": ["supermarket", "mart", "dmart", "more", "spencer", "reliance fresh", "hypermarket", "grocery", "kirana", "కిరాణా", "సూపర్ మార్కెట్", "सुपरमार्केट"],
        "direct_osm_tags": ["shop=supermarket", "shop=grocery", "shop=convenience", "shop=general"],
        "indirect_osm_tags": ["amenity=marketplace", "shop=department_store"],
        "indirect_keywords": ["bazaar", "market", "store"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "amenity=cafe", "shop=dairy", "shop=clothes"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "dhaba", "biryani", "dairy farm", "cowshed", "barber"],
        "supporting_poi_tags": ["highway=bus_stop", "amenity=bank", "amenity=parking"],
        "customer_segments": ["Middle & Upper-Income Residential Households", "Bulk Weekly / Monthly Shoppers"],
        "supplier_categories": ["Direct FMCG Brands", "APMC Mandi Wholesalers", "Cold Storage Dairy Distributors"],
        "infrastructure_requirements": ["Air Conditioned Retail Floor", "Barcode Scanners & POS Billing", "Dedicated Customer Parking"],
        "relevant_demographics": ["Upper-Middle Income Households", "Vehicle Ownership Density"],
        "relevant_environmental_factors": ["Continuous Power for Air Conditioning and Display Freezers"],
        "relevant_risk_factors": ["High Inventory Carrying Cost", "Expiry & Shrinkage Losses"],
        "relevant_price_indicators": ["Monthly Grocery Basket (Family of 4): ₹6,500-₹11,000"],
        "relevant_accessibility_factors": ["Main Arterial Road", "Four-Wheeler & Two-Wheeler Parking"]
    },
    "fruit_shop": {
        "business_name": "Fresh Fruit Stall",
        "category_slug": "retail",
        "search_keywords": ["fruit", "fruits", "juice", "fresh fruit", "పండ్ల దుకాణం", "పండ్లు", "फलों की दुकान", "फल"],
        "competitor_keywords": ["fruit", "fruits", "greengrocer", "fruit stall", "fruit market", "పండ్ల", "పండ్లు", "फल"],
        "direct_osm_tags": ["shop=greengrocer", "shop=farm", "shop=fruits"],
        "indirect_osm_tags": ["shop=convenience", "amenity=marketplace", "shop=supermarket"],
        "indirect_keywords": ["supermarket", "mandi", "market", "grocery"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "amenity=cafe", "shop=dairy", "craft=dairy", "shop=clothes", "shop=mobile_phone"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "dhaba", "biryani", "dairy farm", "milk collection", "repair", "hardware"],
        "supporting_poi_tags": ["highway=bus_stop", "amenity=hospital", "amenity=place_of_worship"],
        "customer_segments": ["Health-conscious Residents", "Hospital Visitors & Attendants", "Temple Devotees", "Daily Family Shoppers"],
        "supplier_categories": ["District APMC Fruit Mandi", "Local Farmers / Orchards", "Wholesale Banana & Apple Commission Agents"],
        "infrastructure_requirements": ["Shaded Stall / Fruit Crates Display", "Digital Weighing Scale", "Misting Water Spray for Freshness"],
        "relevant_demographics": ["Proximity to Hospitals, Temples, and Residential Hubs"],
        "relevant_environmental_factors": ["Summer Heat causing fast ripening and spoilage", "Monsoon Humidity"],
        "relevant_risk_factors": ["Extremely high spoilage risk (3-5 day shelf life)", "Daily Wholesale Price Volatility"],
        "relevant_price_indicators": ["Banana (Dozen): ₹40-₹60", "Apple (1kg): ₹140-₹220", "Pomegranate (1kg): ₹120-₹180"],
        "relevant_accessibility_factors": ["High Pedestrian Footfall Near Hospital, Temple, or Bus Stand"]
    },
    "vegetable_shop": {
        "business_name": "Vegetable & Greens Stall",
        "category_slug": "retail",
        "search_keywords": ["vegetable", "veggies", "greens", "కూరగాయలు", "కూరగాయల కొట్టు", "రైతు బజార్", "सब्जी"],
        "competitor_keywords": ["vegetable", "greengrocer", "rythu bazaar", "subzi", "greens", "కూరగాయలు", "రైతు బజార్", "सब्जी"],
        "direct_osm_tags": ["shop=greengrocer", "shop=farm"],
        "indirect_osm_tags": ["amenity=marketplace", "shop=supermarket", "shop=convenience"],
        "indirect_keywords": ["supermarket", "market", "mandi", "grocery"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "amenity=cafe", "shop=dairy", "shop=clothes"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "dhaba", "dairy farm", "hardware", "repair"],
        "supporting_poi_tags": ["residential=subdivision", "highway=bus_stop"],
        "customer_segments": ["Daily Cooking Households", "Local Eateries & Tiffin Stalls", "Hostels & Mess Facilities"],
        "supplier_categories": ["Local Rythu Mandi / Farmers", "APMC Wholesale Markets"],
        "infrastructure_requirements": ["Clean Water Source for Washing", "Covered Stall with Mesh Protection", "Digital Scale"],
        "relevant_demographics": ["Dense Residential Colony Catchment"],
        "relevant_environmental_factors": ["Daily Heat Stress on Leafy Vegetables"],
        "relevant_risk_factors": ["Daily Unsold Wastage", "High Perishability"],
        "relevant_price_indicators": ["Tomato (1kg): ₹25-₹45", "Onion (1kg): ₹30-₹55", "Potato (1kg): ₹25-₹35"],
        "relevant_accessibility_factors": ["Walking Distance for Homemakers (< 300m)"]
    },
    "poultry_farming": {
        "business_name": "Poultry Farming & Meat",
        "category_slug": "dairy_livestock",
        "search_keywords": ["poultry", "chicken", "broiler", "layer", "egg", "meat", "కోళ్ల ఫారమ్", "చికెన్", "గుడ్లు", "ముర్गी"],
        "competitor_keywords": ["poultry", "chicken", "meat", "broiler", "suguna", "sneha", "egg", "కోళ్ల", "చికెన్", "ముర్गी"],
        "direct_osm_tags": ["shop=butcher", "building=farm", "landuse=farmyard"],
        "indirect_osm_tags": ["amenity=marketplace", "shop=supermarket"],
        "indirect_keywords": ["market", "mandi"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "shop=clothes", "shop=bakery"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "cafe", "fast food", "bakery", "hardware"],
        "supporting_poi_tags": ["amenity=veterinary", "shop=agrarian"],
        "customer_segments": ["Local Non-Veg Consuming Households", "Restaurants, Hotels & Dhaba Kitchens", "Weekly Haat Buyers"],
        "supplier_categories": ["Day-Old Chick (DOC) Hatcheries", "Commercial Poultry Feed Mills", "Veterinary Vaccine Suppliers"],
        "infrastructure_requirements": ["Well-Ventilated Shed with Litter Management", "Clean Borewell Water & Feeders", "Electricity with Generator Backup"],
        "relevant_demographics": ["Distance from Village Abadi (> 500m mandatory)", "Non-Veg Consumption Frequency"],
        "relevant_environmental_factors": ["Extreme Summer Heat (High Mortality Risk)", "Avian Flu Biosecurity Protocols"],
        "relevant_risk_factors": ["Bird Mortality / Epidemic Diseases", "Poultry Feed (Maize/Soya) Price Surges", "Lifting Bird Price Fluctuations"],
        "relevant_price_indicators": ["Live Broiler Farmgate: ₹85-₹115/kg", "Dressed Chicken Retail: ₹180-₹240/kg", "Commercial Table Egg: ₹5.20-₹6.50/pc"],
        "relevant_accessibility_factors": ["All-Weather Feeder Road for Feed and Bird Transport Trucks"]
    },
    "mobile_repair": {
        "business_name": "Mobile Phone Repair",
        "category_slug": "services",
        "search_keywords": ["mobile", "cell phone", "repair", "screen replacement", "మొబైల్ రిపేర్", "ఫోన్ బాగుచేయు", "मोबाइल रिपेयर"],
        "competitor_keywords": ["mobile repair", "cell clinic", "phone service", "smartphone service", "touch screen replacement", "mobile shop", "మొబైల్", "मोबाइल"],
        "direct_osm_tags": ["shop=mobile_phone", "craft=electronics_repair"],
        "indirect_osm_tags": ["shop=electronics", "shop=computer"],
        "indirect_keywords": ["electronics", "computer", "accessories"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "shop=dairy", "shop=supermarket", "shop=grocery"],
        "exclude_keywords": ["restaurant", "hotel", "mess", "dairy", "milk", "supermarket", "mart", "dmart", "more", "kirana"],
        "supporting_poi_tags": ["amenity=college", "amenity=bus_station", "amenity=marketplace"],
        "customer_segments": ["Smartphone Users (Students, Youth, Farmers, Workers)", "Local Businesses & Delivery Agents"],
        "supplier_categories": ["Wholesale Spare Parts Importers (Screens, Batteries, ICs)", "Tool & Microscope Suppliers"],
        "infrastructure_requirements": ["Precision Soldering & SMD Rework Station", "Microscope", "Continuous Power Backup (Inverter)"],
        "relevant_demographics": ["Smartphone Penetration Rate", "Youth & Student Population", "Commercial Workers Count"],
        "relevant_environmental_factors": ["Dust Control in Work Area", "Humidity Protection for Logic Boards"],
        "relevant_risk_factors": ["Rapid Model Obsolescence", "Counterfeit Spare Quality", "Technician Skill Upgradation Needs"],
        "relevant_price_indicators": ["Screen Combo Replacement: ₹900-₹2,800", "Charging Port Repair: ₹150-₹350", "Battery Replacement: ₹500-₹1,200"],
        "relevant_accessibility_factors": ["High-Footfall Market Junction", "Near Bus Station or Main Junction"]
    },
    "solar_maintenance": {
        "business_name": "Solar Panel Cleaning & Maintenance",
        "category_slug": "environment_sustainability",
        "search_keywords": ["solar", "cleaning", "maintenance", "inverter", "pv panel", "సోలార్ క్లీనింగ్", "సౌరశక్తి", "सोलर"],
        "competitor_keywords": ["solar service", "solar maintenance", "pv cleaning", "renewable energy service", "solar solutions", "solar energy", "సోలార్", "सोलर"],
        "direct_osm_tags": ["power=generator", "office=energy_supplier", "craft=electrician"],
        "indirect_osm_tags": ["shop=electrical", "craft=cleaning"],
        "indirect_keywords": ["electrical", "energy", "power"],
        "exclude_osm_tags": ["amenity=restaurant", "amenity=fast_food", "shop=dairy", "shop=supermarket", "shop=grocery"],
        "exclude_keywords": ["restaurant", "hotel", "supermarket", "dmart", "more", "dairy", "milk", "kirana"],
        "supporting_poi_tags": ["landuse=industrial", "landuse=commercial", "amenity=public_building"],
        "customer_segments": ["Rooftop Solar Owners (Commercial & Residential)", "Agricultural Solar Water Pump Farmers", "Industrial Sheds & Warehouses"],
        "supplier_categories": ["De-ionized Water Equipment", "Soft Bristle Telescopic Brushes", "Thermal Imaging & Diagnostic Tools"],
        "infrastructure_requirements": ["Two-Wheeler / Utility Vehicle with Water Tank", "Safety Harness & Ladders", "Electrical Testing Multimeter"],
        "relevant_demographics": ["Installed Solar Capacity in District / Mandal", "Commercial Establishments with Flat Roofs", "Pumpset Density"],
        "relevant_environmental_factors": ["Dust & Agricultural Threshing Fallout", "High Solar Insolation (Andhra Pradesh 5.5 kWh/m²/day)"],
        "relevant_risk_factors": ["Seasonal Client Demand (Post-harvest/Monsoon)", "Safety at Heights", "Untrained Staff Damage Claims"],
        "relevant_price_indicators": ["Residential 3kW-5kW Panel Cleaning: ₹400-₹800/visit", "Commercial MW Scale: ₹18-₹30/panel", "Annual Maintenance Contract (AMC): ₹3,500-₹7,000/yr"],
        "relevant_accessibility_factors": ["Highway Connectivity for Fast Rural Dispatch", "Access to Farm Feeder Roads"]
    }
}
